### ISSUE TITLE
Help running examples

### ISSUE THREAD

**Issue by kspieks** [ZimmermanGroup/pyGSM#9]
Hi Cody,

Thanks so much for creating pyGSM! I’m not familiar with C++ but was interested in incorporating pyGSM into my research. I ran `setup.py` in an environment with Python 3.7 on a linux server that has slurm and QChem, and I believe it installed properly. I’ve been trying to run some of the QChem examples, but was running into errors for loading the modules (line 10 in `slurm.qsh`). Can you help me get this example working?

I also tried reviving one of the old example scripts like `run_de_gsm.py` but I’m not sure if the QChem, Lot, or Option classes are set up correctly since it fails to create the lot on line 31 in `run_de_gsm.py`. Could you help me debug this so I can run the examples? 

Thanks in advance,
Kevin

**Comment by craldaz** [comment]
Try this for DE-GSM, where diels alder is the reactant and product (atoms must be in the same order) gsm  -xyzfile diels_alder.xyz  \    -mode DE_GSM \    -nnodes 11 \    -package QChem \    -lot_inp_file qstart \    -ID $SLURM_ARRAY_TASK_ID \    -coordinate_type DLC > log 2>&1 And qstart is like your input without charge, multiplicity $rem JOBTYPE FORCE EXCHANGE B3LYP SCF_ALGORITHM diis SCF_MAX_CYCLES 150 SCF_CONVERGENCE 6 basis 6-31G* WAVEFUNCTION_ANALYSIS FALSE SYM_IGNORE TRUE SYMMETRY   FALSE XC_GRID 1$end Here is an SE-GSM example. gsm  -xyzfile diels_alder.xyz \    -isomers isomers.txt \    -mode SE_GSM \    -package QChem \    -lot_inp_file qstart \    -ID $SLURM_ARRAY_TASK_ID \    -coordinate_type DLC > log 2>&1 Where isomers.txt is ADD 4 12ADD 1 11  Here is an API example from pygsm.level_of_theories.qchem import QChemfrom pygsm.potential_energy_surfaces import PESfrom pygsm.optimizers import *from pygsm.wrappers import Moleculefrom pygsm.utilities import *from coordinate_systems import Topology,PrimitiveInternalCoordinates,DelocalizedInternalCoordinatesimport numpy as np def main():     geom = manage_xyz.read_xyz("geom.xyz")    xyz = manage_xyz.xyz_to_np(geom)     nifty.printcool(" Building the LOT")    lot = QChem.from_options(            lot_inp_file="qstart",            states=[(1,0)],            geom=geom,            )     nifty.printcool(" Building the PES")    pes = PES.from_options(            lot=lot,            ad_idx=0,            multiplicity=1,            )     nifty.printcool("Building the topology")    atom_symbols  = manage_xyz.get_atoms(geom)    ELEMENT_TABLE = elements.ElementData()    atoms = [ELEMENT_TABLE.from_symbol(atom) for atom in atom_symbols]    top = Topology.build_topology(            xyz,            atoms,            )     nifty.printcool("Building Primitive Internal Coordinates")    p1 = PrimitiveInternalCoordinates.from_options(            xyz=xyz,            atoms=atoms,            addtr=False,  # Add TRIC            topology=top,            )     nifty.printcool("Building Delocalized Internal Coordinates")    coord_obj1 = DelocalizedInternalCoordinates.from_options(            xyz=xyz,            atoms=atoms,            addtr = False,  # Add TRIC            )     nifty.printcool("Building Molecule")    reactant = Molecule.from_options(            geom=geom,            PES=pes,            coord_obj = coord_obj1,            Form_Hessian=True,            )     print(" Done creating molecule")    optimizer = eigenvector_follow.from_options(Linesearch='backtrack',OPTTHRESH=0.0005,DMAX=0.5,abs_max_step=0.5,conv_Ediff=0.5)     print("initial energy is {:5.4f}".format(reactant.energy))    geoms,energies = optimizer.optimize(            molecule=reactant,            refE=reactant.energy,            opt_steps=500,            verbose=True,            )     print("Final energy is {:5.4f}".format(reactant.energy))    manage_xyz.write_xyz('minimized.xyz',geoms[-1],energies[-1],scale=1.) if __name__=='__main__':    main()    Sent from Mail for Windows 10 From: Kevin SpiekermannSent: Friday, September 25, 2020 5:50 PMTo: ZimmermanGroup/pyGSMCc: SubscribedSubject: [ZimmermanGroup/pyGSM] Help running examples (#9) Hi Cody,Thanks so much for creating pyGSM! I’m not familiar with C++ but was interested in incorporating pyGSM into my research. I ran setup.py in an environment with Python 3.7 on a linux server that has slurm and QChem, and I believe it installed properly. I’ve been trying to run some of the QChem examples, but was running into errors for loading the modules (line 10 in slurm.qsh). Can you help me get this example working?I also tried reviving one of the old example scripts like run_de_gsm.py but I’m not sure if the QChem, Lot, or Option classes are set up correctly since it fails to create the lot on line 31 in run_de_gsm.py. Could you help me debug this so I can run the examples? Thanks in advance.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kspieks** [comment]
Thanks for the example code. Looks like the diels alder DE GSM example from the repo is running now :) Hopefully it converges fine. As a few follow-up questions:
- Can you help me understand guidelines for changing the number of nodes from the default value like you did here? 
- Can you help me understand how to properly parallelize the process? I’m confused by the `-nproc` and `-use_multiprocessing` flags. They both reference a `OMP_NUM_THREADS` flag but I'm not seeing that as a command line argument.
- Can you further explain how to search across different conformers/isomers and what goes in the isomers.txt file?


Regarding the API, it looks like it is set up to do unimolecular reactions? Or at least I’m not sure what to do with the second geometry read in from `pyGSM/data/diels_alder.xyz` for example since it looks like 
```
lot = QChem.from_options(lot_inp_file="qstart", states=[(1,0)], geom=geom )
```
is expecting just one geometry in `geom`. Can you clarify how to run bimolecular reactions? Also how do I specify the API to use SE or DE GSM?

Thanks so much,
Kevin

**Comment by craldaz** [comment]
First I'm  repost my email above again since I didn't anticipate that it would look so bad online
----

Try this for DE-GSM, where diels alder is the reactant and product (atoms must be in the same order)

```
 
gsm  -xyzfile diels_alder.xyz  \
    -mode DE_GSM \
    -nnodes 11 \
    -package QChem \
    -lot_inp_file qstart \
    -ID $SLURM_ARRAY_TASK_ID \
    -coordinate_type DLC > log 2>&1

```
 

And qstart is like your input without charge, multiplicity

 

```
$rem
JOBTYPE FORCE
EXCHANGE B3LYP
SCF_ALGORITHM diis
SCF_MAX_CYCLES 150
SCF_CONVERGENCE 6
basis 6-31G*
WAVEFUNCTION_ANALYSIS FALSE
SYM_IGNORE TRUE
SYMMETRY   FALSE
XC_GRID 1
$end
```

 

Here is an SE-GSM example.

```
gsm  -xyzfile diels_alder.xyz \
    -isomers isomers.txt \
    -mode SE_GSM \
    -package QChem \
    -lot_inp_file qstart \
    -ID $SLURM_ARRAY_TASK_ID \
    -coordinate_type DLC > log 2>&1
```

 

Where isomers.txt is

```
ADD 4 12
ADD 1 11

```
 

 

Here is an API example

 
```
from pygsm.level_of_theories.qchem import QChem
from pygsm.potential_energy_surfaces import PES
from pygsm.optimizers import *
from pygsm.wrappers import Molecule
from pygsm.utilities import *
from coordinate_systems import Topology,PrimitiveInternalCoordinates,DelocalizedInternalCoordinates
import numpy as np


def main(): 
    geom = manage_xyz.read_xyz("geom.xyz")
    xyz = manage_xyz.xyz_to_np(geom)

    nifty.printcool(" Building the LOT")
    lot = QChem.from_options(
            lot_inp_file="qstart",
            states=[(1,0)],
            geom=geom,
            )

    nifty.printcool(" Building the PES")
    pes = PES.from_options(
            lot=lot,
            ad_idx=0,
            multiplicity=1,
            )

    nifty.printcool("Building the topology")
    atom_symbols  = manage_xyz.get_atoms(geom)
    ELEMENT_TABLE = elements.ElementData()
    atoms = [ELEMENT_TABLE.from_symbol(atom) for atom in atom_symbols]
    top = Topology.build_topology(
            xyz,
            atoms,
            )
 
    nifty.printcool("Building Primitive Internal Coordinates")
    p1 = PrimitiveInternalCoordinates.from_options(
            xyz=xyz,
            atoms=atoms,
            addtr=False,  # Add TRIC
            topology=top,
            )

    nifty.printcool("Building Delocalized Internal Coordinates")
    coord_obj1 = DelocalizedInternalCoordinates.from_options(
            xyz=xyz,
            atoms=atoms,
            addtr = False,  # Add TRIC
            )

    nifty.printcool("Building Molecule")
    reactant = Molecule.from_options(
            geom=geom,
            PES=pes,
            coord_obj = coord_obj1,
            Form_Hessian=True,
            )

    print(" Done creating molecule")
    optimizer = eigenvector_follow.from_options(Linesearch='backtrack',OPTTHRESH=0.0005,DMAX=0.5,abs_max_step=0.5,conv_Ediff=0.5)

    print("initial energy is {:5.4f}".format(reactant.energy))
    geoms,energies = optimizer.optimize(
            molecule=reactant,
            refE=reactant.energy,
            opt_steps=500,
            verbose=True,
            )

    print("Final energy is {:5.4f}".format(reactant.energy))
    manage_xyz.write_xyz('minimized.xyz',geoms[-1],energies[-1],scale=1.)

if __name__=='__main__':
    main()
```

**Comment by craldaz** [comment]
>     Can you help me understand guidelines for changing the number of nodes from the default value like you did here?

We usually use 9 or 11 for DE-GSM. It doesn't matter very much but if the reaction path is "very" long then using more might be better. SE-GSM determines how many nodes it needs. The `DQMAG_MAX` keyword controls the stepsize that SE-GSM grows nodes. The default is 0.6 I believe. Using 0.4 can be useful to get a finer interpolation. 0.8 can be useful for larger systems as the reaction path will be coarser. 

    `Can you help me understand how to properly parallelize the process? I’m confused by the -nproc and -use_multiprocessing flags. They both reference a OMP_NUM_THREADS flag but I'm not seeing that as a command line argument.`

Ignore the multiprocessing flag, it's not used. If `OMP_NUM_THREADS` is set pyGSM will attempt to use that for `nprocs` which is what will tell Q-Chem to run in parallel. Otherwise you can explicitly say how many processors to use and Q-Chem will attempt to use that. There is no other parallelism in the code currently. 

> 
    Can you further explain how to search across different conformers/isomers and what goes in the isomers.txt file?

`-isomers` keyword does not refer to conformers/isomers. This is a misnomer that is vestigial from the previous code. It refers to the driving coordinate. The driving coordinate file can contain "ADD" "BREAK", "ANGLE" and "TORSION" moves. For example, 
ADD atoms 4 and 12 ==> ADD 4 12

More info can be found in the main.py file. ADD and BREAK require only 2 indices but an optional distance value can be given. ANGLE and TORSION require 3 and 4 indices respectively and require an ANGLE value. 



> Regarding the API, it looks like it is set up to do unimolecular reactions? Or at least I’m not sure what to do with the second geometry read in from pyGSM/data/diels_alder.xyz for example since it looks like
> 
> lot = QChem.from_options(lot_inp_file="qstart", states=[(1,0)], geom=geom )
> 
> is expecting just one geometry in geom. Can you clarify how to run bimolecular reactions? Also how do I specify the API to use SE or DE GSM?
> 

The API example is just a simple geometry optimization -- no GSM. It is just to illustrate some of the underlying functionality. The "API" for GSM can be found in main.py.

**Comment by craldaz** [comment]
This information is now included in the wiki.
